In [2]:
import pandas as pd
import numpy as np
import random

In [3]:
# Set random seed for reproducibility
np.random.seed(42)

In [4]:
# Generate sample data
data = {
    'ID': range(1, 501),
    'Age': np.random.randint(18, 80, 500),
    'Gender': np.random.choice(['Male', 'Female', 'Other'], 500),
    'Ethnicity': np.random.choice(['White', 'Black', 'Asian', 'Hispanic', 'Other'], 500),
    'Income': np.random.randint(20000, 120000, 500),
    'Education Level': np.random.choice(['High School', 'Associate', 'Bachelor', 'Master', 'Doctorate'], 500),
    'Smoking Status': np.random.choice(['Never', 'Former', 'Current'], 500),
    'Physical Activity': np.random.randint(0, 7, 500),
    'BMI': np.random.uniform(18.5, 40.0, 500).round(1),
    'Chronic Conditions': np.random.choice(['None', 'Diabetes', 'Hypertension', 'Diabetes and Hypertension'], 500),
    'Mental Health Status': np.random.choice(['Poor', 'Fair', 'Good', 'Very Good', 'Excellent'], 500),
    'Access to Healthcare': np.random.choice(['Easy', 'Moderate', 'Difficult'], 500),
    'Health Insurance': np.random.choice(['None', 'Private', 'Public'], 500),
    'Vaccination Status': np.random.choice(['Yes', 'No'], 500),
    'Health Satisfaction': np.random.randint(1, 11, 500)
}

In [5]:
# Create DataFrame
df = pd.DataFrame(data)

In [6]:
# Save to CSV
df.to_csv('Wayne_County_Health_and_Wellbeing_Survey_2024.csv', index=False)

print("CSV file has been created.")

CSV file has been created.

In [7]:
df

,ID,Age,Gender,Ethnicity,Income,Education Level,Smoking Status,Physical Activity,BMI,Chronic Conditions,Mental Health Status,Access to Healthcare,Health Insurance,Vaccination Status,Health Satisfaction
0,1,56,Female,Asian,106123,Associate,Never,4,24.0,Hypertension,Good,Easy,Private,No,1
1,2,69,Other,Hispanic,95186,Associate,Current,4,19.8,Diabetes and Hypertension,Excellent,Moderate,Public,No,4
2,3,46,Female,Hispanic,105469,Bachelor,Former,1,31.5,None,Good,Moderate,Private,Yes,9
3,4,32,Other,White,40581,High School,Former,3,33.3,None,Very Good,Moderate,Private,No,2
4,5,60,Other,Asian,108929,Master,Never,1,21.0,Diabetes,Fair,Moderate,Public,Yes,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,63,Other,White,118762,High School,Current,0,36.7,None,Fair,Easy,None,Yes,3
496,497,41,Other,Asian,66163,Master,Former,2,34.2,Diabetes,Excellent,Moderate,Public,No,2
497,498,67,Other,Asian,118511,Doctorate,Current,5,20.6,None,Excellent,Easy,None,No,1
498,499,49,Male,Black,86435,Master,Never,6,27.7,Hypertension,Fair,Moderate,Public,No,4
499,500,64,Other,Other,31653,Master,Never,5,19.1,Hypertension,Excellent,Easy,None,No,5

In [8]:
df.head()

,ID,Age,Gender,Ethnicity,Income,Education Level,Smoking Status,Physical Activity,BMI,Chronic Conditions,Mental Health Status,Access to Healthcare,Health Insurance,Vaccination Status,Health Satisfaction
0,1,56,Female,Asian,106123,Associate,Never,4,24.0,Hypertension,Good,Easy,Private,No,1
1,2,69,Other,Hispanic,95186,Associate,Current,4,19.8,Diabetes and Hypertension,Excellent,Moderate,Public,No,4
2,3,46,Female,Hispanic,105469,Bachelor,Former,1,31.5,None,Good,Moderate,Private,Yes,9
3,4,32,Other,White,40581,High School,Former,3,33.3,None,Very Good,Moderate,Private,No,2
4,5,60,Other,Asian,108929,Master,Never,1,21.0,Diabetes,Fair,Moderate,Public,Yes,3